apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-bedrock-server.fullname" . }}
  labels:
    {{- include "minecraft-bedrock-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 19132
      protocol: UDP
  selector:
    {{- include "minecraft-bedrock-server.selectorLabels" . | nindent 4 }}
